name: Artifacts workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use upload-artifact@v3 to upload the first artifact...
      - name: Upload artifact1
        uses: actions/upload-artifact@v3
        with:
          name: artifact1
          path: 'artifact1.txt'
      # ... and upload-artifact@v4 to upload the second one.
      # These are completely different infrastructure and we need to support both.
      # See https://github.com/hub4j/github-api/issues/1790 for more context
      - name: Upload artifact2
        uses: actions/upload-artifact@v4
        with:
          name: artifact2
          path: 'artifact2.txt'
